ljtill/pipelines

- src/Pipelines.Runtime/Functions/Process.cs
Rename the Request function to Process function
> refactor: rename request function with process

- README.md
Update project structure with images artifacts relocation
> refactor: update project structure content

- src/Pipelines.Runtime/Clients/Kubernetes/ClusterClient.cs
- src/Pipelines.Runtime/Clients/Kubernetes/KubernetesClient.cs
- src/Pipelines.Runtime/Functions/Create.cs
- src/Pipelines.Runtime/Services/Kubernetes/ClusterService.cs
Remove KubernetesClient class abstraction
> refactor: remove kubernetesclient abstraction

- src/Pipelines.Runtime/Makefile
Add `Makefile` with Deploy & Destroy targets to support Getting Started process
> refactor: add makefile for deploying and destroying

- eng/infra/Makefile
- eng/infra/README.md
- eng/infra/bicepconfig.json
- eng/infra/modules/clusters/resources.bicep
- eng/infra/modules/clusters/resources.diagnostics.bicep
- eng/infra/modules/endpoints/resources.bicep
- eng/infra/modules/endpoints/resources.namespaces.bicep
- eng/infra/modules/endpoints/resources.registries.bicep
- eng/infra/modules/endpoints/resources.storage.bicep
- eng/infra/modules/endpoints/resources.vaults.bicep
- eng/infra/modules/groups/resources.bicep
- eng/infra/modules/services/resources.bicep
- eng/infra/modules/services/resources.diagnostics.bicep
- eng/infra/modules/zones/resources.bicep
- eng/infra/region.bicep
- eng/infra/scripts/bootstrap.sh
Add `infra/` source code from Git submodule repository (ljtill/pipelines-infra).
> chore: add infra/ source code from submodule repository

- .gitmodules
- Remove `config/` git submodule
- Remove `tools/` git submodule
- Remove `.gitmodules` file
> chore: remove git submodules

- src/Pipelines.Images/Makefile
Update tabs to spaces to fix Makefile condition blocks
> fix: update tabs to spaces to fix condition blocks in images makefile

- eng/infra/region.bicep
- Fix broken config file path after Git submodule removal
> fix: update config file path

- eng/infra/Makefile
- src/Pipelines.Images/Makefile
- src/Pipelines.Runtime/Makefile
- Update all `Makefile` entities with conditional variable target
- Fix config file path for the `destroy:` target
- Update error message for environment variable failures
> fix: add variable condition blocks

- eng/infra/Makefile
- src/Pipelines.Images/Makefile
- src/Pipelines.Runtime/Makefile
- Update variable checks to bash if conditions
- Update log messages to standard format
- Update config paths for `destroy` target
> fix: switch to bash if conditions

- eng/infra/Makefile
- src/Pipelines.Images/Makefile
- src/Pipelines.Runtime/Makefile
- Update error syntax with exit code termination
> fix: replace error syntax with exit code

- eng/scripts/extension.sh
- eng/scripts/images.sh
- eng/scripts/platform.sh
- eng/scripts/runtime.sh
- Update shell scripts after linter review
- Remove unnecessary environment variables
- Refactor environment variables validation logic
> chore: review syntax with shell script linter

- eng/platform/modules/clusters/resources.bicep
- eng/platform/region.bicep
- Update '/configs/' file path
- Fix linter warning message
> fix: update configs file path

- eng/platform/Makefile
- eng/scripts/platform.sh
- src/Pipelines.Extension/Makefile
- src/Pipelines.Images/Makefile
- src/Pipelines.Runtime/Makefile
- Suppress command out on invocation in `Makefile`
- Remove additional blank space from log message
> chore: suppress command output

- eng/configs/platform.json
- eng/configs/platform.schema.json
Update `$schema` with new `configs` route
> fix: update schema url with new route path

- eng/configs/platform.json
- eng/configs/platform.schema.json
- Remove `zones` & `endpoints` from sample `platform.json` file
- Remove `zones` & `endpoints` from schema
> refactor: remove endpoints & zones objects

- eng/platform/Makefile
- eng/scripts/platform.sh
- eng/scripts/template.sh
- Remove unnecessary `Makefile` targets
- Remove `template.sh` file
- Update autoscaler bootstrap function
- Update identity bootstrap function
> refactor: update e2e bootstrap process

- eng/configs/platform.json
- eng/configs/platform.schema.json
- Remove `description` field from configuration sample and schema
> refactor: remove unused description field

- eng/scripts/images.sh
- eng/scripts/platform.sh
- eng/scripts/runtime.sh
- src/Pipelines.Extension/Makefile
- src/Pipelines.Images/Makefile
- src/Pipelines.Runtime/Makefile
- Draft initial scripts source
> refactor: implement base scripts functionality

- eng/scripts/runtime.sh
- src/Pipelines.Runtime/.gitignore
- src/Pipelines.Runtime/Makefile
- src/Pipelines.Runtime/functions.yaml
- Update `.gitignore` to not exclude `functions.yaml`
- Add base Kubernetes manifest `functions.yaml`
- Remove env vars from `runtime.sh`
- Add generate function to shell script
- Add generate target to `Makefile`
> refactor: end-to-end runtime scripts

- src/Pipelines.Runtime/Pipelines.Runtime.csproj
Pipelines.Runtime
- Update Microsoft.Azure.WebJobs.Extensions.ServiceBus
> chore: update package dependencies

- Pipelines.sln
- Remove `Pipelines.Client` from the .NET Solution list
> chore: update dotnet solution list

- eng/platform/modules/services/resources.bicep
- Dynamically generate an array list from config data and provide the object as a list of ip rules
> refactor: switch to array for client addresses

- eng/scripts/runtime.sh
- src/Pipelines.Runtime/Makefile
- Fix all shellcheck linter warnings
- Update `Makefile` targets
> style: fix linter warnings

- eng/scripts/platform.sh
- Update bootstrap process to handle workload identities
> refactor: develop bootstrap process

- eng/platform/Makefile
- eng/scripts/platform.sh
- Remove deprecated targets
- Remove identity and autoscaler functions
- Add subscription selection logic
- Update logging message
- Remove unused invocation blocks
> refactor: platform artifacts

- eng/scripts/runtime.sh
- src/Pipelines.Runtime/Clients/ClusterClient.cs
- src/Pipelines.Runtime/Functions/Process.cs
- src/Pipelines.Runtime/Helpers/KubernetesHelper.cs
- src/Pipelines.Runtime/Models/ApplicationProperties.cs
- Remove username from all `TODO:` comments across the codebase
> chore: remove username from todo comments

- eng/platform/modules/clusters/resources.bicep
- Remove the dependency to purge Key Vault resources before new deployment
- Remove `createMode` option from resource
- Add `enableSoftDelete` option to resource
> feat: remove keyvault purge dependency

- eng/platform/region.bicep
- eng/scripts/extension.sh
- eng/scripts/platform.sh
- eng/scripts/runtime.sh
- Prerequisite for workload identity role assignment 
- Add `appId` parameter to resource deployment
- Replace `json()` with `loadJsonContent()` function
- Add code comments across scripts
> feat: inject appid as part of resource deployment

- eng/platform/modules/clusters/resources.bicep
- eng/platform/region.bicep
- eng/scripts/platform.sh
- Rename Bicep parameter to `applicationId`
- Add workload identity role assignments
> feat: add workload identity role assignments

- eng/configs/platform.json
- eng/configs/platform.schema.json
- eng/platform/modules/services/resources.bicep
- Replace `clientAddresses` type from string to array
- Replace `ipRules` logic to follow cluster design
> fix: update clientaddress type

- eng/platform/modules/clusters/resources.bicep
- Add `scope` property to each role assignment resource
> fix: add scope property to role assignments

- eng/platform/modules/clusters/resources.bicep
- Remove public access to services
- Add client addresses to network access control lists
> fix: remove public access to storage account

- eng/platform/modules/clusters/resources.bicep
- Remove `inboundConnections` array from the `ipRules` property
> fix: remove unnecessary ip rule injection

- eng/configs/platform.json
- eng/configs/platform.schema.json
- Update schema with new required properties
> chore: revise configs schema structure

- eng/scripts/platform.sh
- Refine logging messages for azure active directory interaction
> chore: update platform logging messages

- eng/platform/main.bicep
- eng/platform/modules/clusters/resources.bicep
- eng/scripts/platform.sh
- Replace Application `applicationId` value with Service Principal `objectId`
> fix: replace applicationid with objectid property

- eng/scripts/platform.sh
- Update the execution order so that the object-id is retrieved after being created
> fix: update object-id execution order

- eng/scripts/extension.ps1
- eng/scripts/images.ps1
- eng/scripts/platform.ps1
- eng/scripts/runtime.ps1
Added PowerShell scripts for the following shell scripts: images.sh, runtime.sh, platform.sh, and extension.sh
> PowerShell Scripts

- eng/scripts/extension.ps1
- eng/scripts/images.ps1
- eng/scripts/platform.ps1
- eng/scripts/runtime.ps1
- Run the PowerShell linter against the `.ps1` scripts
> chore: powershell linter

- eng/configs/platform.json
- eng/configs/platform.schema.json
- Add new `clusterType` property to the structure
> chore: generate new json schema for config files

- eng/platform/modules/clusters/private/resources.assignments.bicep
- eng/platform/modules/clusters/private/resources.components.bicep
- eng/platform/modules/clusters/public/resources.assignments.bicep
- eng/platform/modules/clusters/public/resources.components.bicep
- eng/platform/modules/clusters/resources.bicep
- Decouple role assignments into separate files
> feat: split role assignments

- src/Pipelines.Runtime/functions.yaml
Added pull policy for runtime manifest
> fix: pull policy to runtime manifest

- eng/platform/modules/clusters/private/resources.components.bicep
- eng/platform/modules/clusters/public/resources.components.bicep
Added client IPs to IP rules for storage account, KeyVault and clusters
> feat: authorized ip ranges for kubernetes clusters
